[connections.streamlit_db]
url = "sqlite:///streamlit.db"

[connections.neon_db]
url = "postgresql://dennis:0M7vglpmoFCE@ep-calm-star-072623.ap-southeast-1.aws.neon.tech/cdm?sslmode=requireoptions=-csearch_path%3Ddbo,streamlit"

[connections.local_postgresql]
url = "postgresql://postgres:password@192.168.1.3:5432/insight_studio_staging?options=-csearch_path%3Ddbo,streamlit"

[connections.local_db_external]
url = "postgresql://postgres:password@postgres.dennis-dta.com/insight_studio_staging?options=-csearch_path%3Ddbo,streamlit"